name: ConnectBestServer
version: '${version}'
main: tw.brilliant.server.plugins.connectbestserver.ConnectBestServer
api-version: 1.19
authors: [ SiongSng ]
description: Automatically connect to the best server in bungeecord.
website: brilliantw.net
